### ISSUE TITLE
<colorchat>

### ISSUE THREAD

**Issue by armync** [OciXCrom/IPShower#1]
Why do you added "#include <colorchat>" as in AMXX 1.8.3 is already included. I miss something?

**Comment by OciXCrom** [comment]
@ArmynC - AMXX 1.8.3 isn't officially released yet. Most people still use 1.8.2, so if I don't include this, the plugin will be available only for people using 1.8.3 dev builds.

**Comment by armync** [comment]
You could add something like: if amxmodx <1.8.3 -> include <colorchat> else continue..

+ I can't delete it because it will give me some errors..

**Comment by OciXCrom** [comment]
The colorchat include and the 1.8.3 functions don't use the same syntax so it can't be done with only one check. Having a colorchat library is not a problem even if you're using 1.8.3. It won't destroy your server or anything.

**Comment by armync** [comment]
Yeah I know but if 1.8.3 support it I don't want to use it.. like I don't really wana it in include just for 1 plugin :( Any update in the future?

**Comment by armync** [comment]
So.. can you make without the need of colorchat?

**Comment by OciXCrom** [comment]
I'm not going to waste my time with releasing 2 different versions for every single one of my plugins just because you don't want to have an additional include file whose size is 2 KB. This is the most ridiculous thing I've ever heard.

**Comment by armync** [comment]
No to release different versions just to do multicompatible versions like other plugins.

**Comment by armync** [comment]
See this

#if AMXX_VERSION_NUM < 183
    #include <colorchat>
    
    #define print_team_default DontChange
    #define print_team_grey Grey
    #define print_team_red Red
    #define print_team_blue Blue
    
    #define MAX_PLAYERS 32
    #define MAX_NAME_LENGTH 32
    
    #define client_disconnected client_disconnect
#endif

**Comment by armync** [comment]
I manage to make it.. 

[ip_shower.txt](https://github.com/OciXCrom/IPShower/files/1675001/ip_shower.txt)

**Comment by OciXCrom** [comment]
This is one of my few un-updated plugins in which I still use the colorchat library. In my newer plugins I use a different colorchat library (cromchat) that has different color symbols (&x04 instead of ^x04), so there's no chance that I'm going to add any support for 1.8.3 there. And, again - **there is nothing wrong with using an additional library**.
